import {
  Trophy,
  Award,
  Zap,
  Heart,
  Briefcase,
  Book,
  Coffee,
  Sunrise,
  Target,
  TrendingUp,
  BookOpen,
} from "lucide-react";

export const achievementsData = [
  // Conquistas Bronze
  {
    id: 1,
    title: "Seu quarto, sua mente",
    description: "Arrume o seu quarto uma vez por semana por 1 mês",
    category: "Produtividade",
    tier: "bronze",
    points: 10,
    icon: Sunrise,
  },
  {
    id: 2,
    title: "Hmmm refreshing",
    description: "Beba 2 litros de água todos os dias por 1 mês",
    category: "Saúde",
    tier: "bronze",
    points: 10,
    icon: Coffee,
  },
  {
    id: 3,
    title: "Declínio de ...",
    description: "Leia um livro inteiro em 1 mês",
    category: "Conhecimento",
    tier: "bronze",
    points: 10,
    icon: Book,
  },
  {
    id: 4,
    title: "Mate a saudade",
    description: "Ligue para um familiar",
    category: "Social",
    tier: "bronze",
    points: 10,
    icon: Heart,
  },

  // Conquistas Prata
  {
    id: 5,
    title: "Mais inteligente que uma porta!",
    description: "Estude para o NEEJA durante o ano",
    category: "Produtividade",
    tier: "prata",
    points: 25,
    icon: BookOpen,
  },
  {
    id: 6,
    title: "Mestre da Organização",
    description: "Reorganize o seu quarto, mude o layout",
    category: "Produtividade",
    tier: "prata",
    points: 25,
    icon: Target,
  },
  {
    id: 7,
    title: "Lili leitora",
    description: "Termine uma saga de livros completa",
    category: "Conhecimento",
    tier: "prata",
    points: 25,
    icon: Book,
  },
  {
    id: 8,
    title: "Flexibilidade",
    description: "Pratique algum exercício todos os dias por 1 mês",
    category: "Saúde",
    tier: "prata",
    points: 25,
    icon: Zap,
  },

  // Conquistas Ouro
  {
    id: 9,
    title: "No caminho!",
    description: "Passe no NEEJA",
    category: "Conhecimento",
    tier: "ouro",
    points: 50,
    icon: Book,
  },
  {
    id: 10,
    title: "Adeus McLonalds...",
    description: "Troque de emprego",
    category: "Carreira",
    tier: "ouro",
    points: 50,
    icon: Briefcase,
  },
  {
    id: 11,
    title: "Sem medo do desconhecido",
    description: "Comece um hobby novo",
    category: "Saúde",
    tier: "ouro",
    points: 50,
    icon: TrendingUp,
  },

  {
    id: 12,
    title: "Onde tudo começou",
    description: "Adquira a Laufey",
    category: "Saúde",
    tier: "ouro",
    points: 50,
    icon: TrendingUp,
  },
  {
    id: 13,
    title: "Masterchef",
    description: "Cozinhe algo maneiro por mês durante um ano",
    category: "Social",
    tier: "ouro",
    points: 50,
    icon: Heart,
  },

  // Conquistas Platina
  {
    id: 14,
    title: "Meu orgulho",
    description: "Se forme como veterinária (ou trabalhe na área)",
    category: "Realização",
    tier: "platina",
    points: 100,
    icon: Trophy,
  },
  {
    id: 15,
    title: "Lili do Pikirido",
    description: "Conclua todas as conquistas",
    category: "Realização",
    tier: "platina",
    points: 100,
    icon: Award,
  },
];

export const categories = [
  "Todas",
  "Saúde",
  "Conhecimento",
  "Social",
  "Produtividade",
  "Carreira",
  "Realização",
];
